### ISSUE TITLE
After Update to 3.0 LG TV is not available

### ISSUE THREAD

**Issue by Kohle81** [grzegorz914/homebridge-lgwebos-tv#218]
Hi,
after Update from  v2.20.4 to v3.0.0 and v3.0.1
my LG TV doesn‘t work with Homekit.

I use a Raspberry 4.

homebridge@v1.8.4
UI@v4.56.4
node@v20.16.0

Here is a log after restart Plugin:

`14/08/2024, 21:23:12] [homebridge-lgwebos-tv] Process Ended. Code: 1, Signal: null
[14/08/2024, 21:23:12] [Homebridge UI] Running Command: sudo -E -n npm install -g homebridge-lgwebos-tv@2.20.4
[14/08/2024, 21:23:19] [homebridge-lgwebos-tv] Restarting Process...
[14/08/2024, 21:23:20] [homebridge-lgwebos-tv] Launched child bridge with PID 20895
Error: Cannot find module 'ee-first'
Require stack:
- /usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/on-finished/index.js
- /usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/finalhandler/index.js
- /usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/express/lib/application.js
- /usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/express/lib/express.js
- /usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/express/index.js
- /usr/local/lib/node_modules/homebridge-lgwebos-tv/src/restful.js
- /usr/local/lib/node_modules/homebridge-lgwebos-tv/src/lgwebosdevice.js
- /usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/childBridgeFork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/on-finished/index.js:24:13)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
[14/08/2024, 21:23:20] [homebridge-lgwebos-tv] Child bridge process ended
[14/08/2024, 21:23:20] [homebridge-lgwebos-tv] Process Ended. Code: 1, Signal: null
[14/08/2024, 21:23:27] [homebridge-lgwebos-tv] Restarting Process...
[14/08/2024, 21:23:27] [homebridge-lgwebos-tv] Restarting child bridge...
[14/08/2024, 21:23:27] [homebridge-lgwebos-tv] Child bridge process ended
[14/08/2024, 21:23:27] [homebridge-lgwebos-tv] Process Ended. Code: null, Signal: SIGTERM
[14/08/2024, 21:23:34] [homebridge-lgwebos-tv] Restarting Process...
[14/08/2024, 21:23:36] [homebridge-lgwebos-tv] Launched child bridge with PID 20912
[14/08/2024, 21:23:36] Registering platform 'homebridge-lgwebos-tv.LgWebOsTv'
[14/08/2024, 21:23:36] [homebridge-lgwebos-tv] Loaded homebridge-lgwebos-tv v2.20.4 child bridge successfully
[14/08/2024, 21:23:36] Loaded 0 cached accessories from cachedAccessories.0E5CAC75B721.
[14/08/2024, 21:23:36] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-lgwebos-tv) is running on port 59607.
[14/08/2024, 21:23:36]  `

**Comment by grzegorz914** [comment]
Debug Please.

**Comment by Kohle81** [comment]
Sorry, here the debug log:

`NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[15/08/2024, 12:26:01] [homebridge-lgwebos-tv] Device: 192.168.178.27 LG TV, debug: Plugin send heartbeat to TV.
[15/08/2024, 12:26:11] [homebridge-lgwebos-tv] Device: 192.168.178.27 LG TV, debug: Plugin send heartbeat to TV.

/usr/local/lib/node_modules/homebridge-lgwebos-tv/src/lgwebosdevice.js:583
                const restFulEnabled = device.restFul.enable || false;
                                                      ^
TypeError: Cannot read properties of undefined (reading 'enable')
    at LgWebOsSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/src/lgwebosdevice.js:583:55)
    at LgWebOsSocket.emit (node:events:519:28)
    at LgWebOsSocket.prepareAccessory (/usr/local/lib/node_modules/homebridge-lgwebos-tv/src/lgwebossocket.js:835:18)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/src/lgwebossocket.js:754:95)
[15/08/2024, 12:26:12] [homebridge-lgwebos-tv] Child bridge process ended
[15/08/2024, 12:26:12] [homebridge-lgwebos-tv] Process Ended. Code: 1, Signal: null
[15/08/2024, 12:26:19] [homebridge-lgwebos-tv] Restarting Process...
[15/08/2024, 12:26:20] [homebridge-lgwebos-tv] Launched child bridge with PID 9395
[15/08/2024, 12:26:20] Registering platform 'homebridge-lgwebos-tv.LgWebOsTv'
[15/08/2024, 12:26:20] [homebridge-lgwebos-tv] Loaded homebridge-lgwebos-tv v3.0.1 child bridge successfully
[15/08/2024, 12:26:20] Loaded 0 cached accessories from cachedAccessories.0E5CAC75B721.
[15/08/2024, 12:26:20] [homebridge-lgwebos-tv] Device: 192.168.178.27 LG TV, did finish launching.
[15/08/2024, 12:26:20] [homebridge-lgwebos-tv] Device: 192.168.178.27 LG TV, Config: {
  "name": "LG TV",
  "host": "192.168.178.27",
  "mac": "24:E8:53:8A:D3:7C",
  "getInputsFromDevice": false,
  "disableLoadDefaultInputs": false,
  "filterSystemApps": false,
  "inputsDisplayOrder": 1,
  "inputs": [
    {
      "name": "Netflix",
      "reference": "netflix",
      "mode": 0
    },
    {
      "name": "Disney+",
      "reference": "com.disney.disneyplus-prod",
      "mode": 0
    },
    {
      "name": "YouTube",
      "reference": "youtube.leanback.v4",
      "mode": 0
    },
    {
      "name": "Prime Video",
      "reference": "amazon",
      "mode": 0
    },
    {
      "name": "O2 TV",
      "reference": "tv.waipu.app.o2-lg",
      "mode": 0
    },
    {
      "name": "WOW",
      "reference": "de.sky.skyonline",
      "mode": 0
    },
    {
      "name": "maxdome",
      "reference": "maxdome",
      "mode": 0
    },
    {
      "name": "Joyn",
      "reference": "joyn",
      "mode": 0
    }
  ],
  "buttons": [
    {
      "namePrefix": false
    }
  ],
  "sensorPower": false,
  "sensorPixelRefresh": false,
  "sensorVolume": false,
  "sensorMute": false,
  "sensorInput": false,
  "sensorChannel": false,
  "sensorSoundMode": false,
  "sensorSoundOutput": false,
  "sensorPictureMode": false,
  "sensorScreenOnOff": false,
  "sensorScreenSaver": false,
  "sensorInputs": [
    {
      "namePrefix": false
    }
  ],
  "turnScreenOnOff": true,
  "turnScreenSaverOnOff": false,
  "brightnessControl": false,
  "backlightControl": false,
  "contrastControl": false,
  "colorControl": false,
  "pictureModeControl": false,
  "pictureModes": [
    {
      "namePrefix": false
    }
  ],
  "volumeControlNamePrefix": false,
  "volumeControl": 1,
  "soundModeControl": false,
  "soundModes": [
    {
      "namePrefix": false
    }
  ],
  "soundOutputControl": false,
  "serviceMenu": false,
  "sslWebSocket": false,
  "disableTvService": false,
  "ezAdjustMenu": false,
  "infoButtonCommand": "MENU",
  "enableDebugMode": true,
  "disableLogInfo": false,
  "disableLogDeviceInfo": false,
  "enableRestFul": false,
  "restFulDebug": false,
  "enableMqtt": false,
  "mqttDebug": false,
  "mqttAuth": false,
  "mqtt": {
    "user": "removed",
    "passwd": "removed"
  }
}
[15/08/2024, 12:26:20] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-lgwebos-tv) is running on port 59607.
[15/08/2024, 12:26:20] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0 `

**Comment by Kohle81** [comment]
[homebridge-lgwebos-tv.log.txt](https://github.com/user-attachments/files/16624308/homebridge-lgwebos-tv.log.txt)

**Comment by mjfrey** [comment]
I am getting the same exact error.  Rolled back to previous version.

**Comment by grzegorz914** [comment]
fixed with 3.0.2
